language: csharp
solution: src/GraspIt.sln
install:
  - nuget restore src/GraspIt.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/GraspIt.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/GraspIt.Test/bin/Release/GraspIt.Test.dll
